### ISSUE TITLE
How to use filtered

### ISSUE THREAD

**Issue by PatrickElsingDev** [ongr-io/ElasticsearchDSL#114]
Is there a way to set filtered node in query node?

Example Query: 
`{
    "query":{
        "filtered":{
            "query":{
                "query_string":{
                    "query":"test",
                     "fields": ["title", "content","abstract","page_title_s"],
                     "minimum_should_match":"30%"
                }
            },
            "filter":{
                "bool":{
                    "should":[
                        { "term":{ "CType":"bullets" } },
                        { "term":{ "CType":"text" } },
                        { "term":{ "CType":"textpic" } },
                        { "term":{ "CType":"header" } },
                        { "term":{ "CType":"table" } }
                    ]
                }
            }
        }
    }
}`

**Comment by saimaz** [comment]
Hey @PatrickElsingDev, unfortunately, filtered query is deprecated (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-filtered-query.html) and will be removed in future versions of elasticsearch. Use bool query with the filter instead.

I guess this should work:

```php
        $search = new Search();

        $queryString = new QueryStringQuery(
            'test',
            [
                'fields' => ['title', 'content'],
                'minimum_should_match' => '30%'
            ]
        );

        $termBullets = new TermQuery('CType', 'bullets');
        $termText = new TermQuery('CType', 'text');
        $boolFilter = new BoolQuery();
        $boolFilter->add($termBullets, BoolQuery::SHOULD);
        $boolFilter->add($termText, BoolQuery::SHOULD);
        
        $query = new BoolQuery();
        $query->add($queryString);
        $query->add($boolFilter, BoolQuery::FILTER);

        $search->addQuery($query);
```

**Comment by saimaz** [comment]
I assume it solves the problem so I'm closing the issue.

**Comment by PatrickElsingDev** [comment]
Sorry for not reply to your solution.
Yes it solves my Problem perfectly. 
Thank you!
