### ISSUE TITLE
There is no possibility to add top level inner hits.

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/ElasticsearchDSL#118]
More info here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-inner-hits.html#top-level-inner-hits

**Comment by mvar** [comment]
It would be nice to have parameters support in [Search](https://github.com/ongr-io/ElasticsearchDSL/blob/692828670e8a74f9b38d146ce03273ed098440b5/src/Search.php#L759) class. That should help to avoid similar problems in the future.

**Comment by einorler** [comment]
Yes it would, but only partialy. This is quite a big issue and support for inner hits may need a separate endpoint, because if one would have only parameter support, it would require ~10 level deep multidimensional arrays to implement top level inner hits.
