### ISSUE TITLE
ReversedNestedAggregation cannot be used without inner aggregations

### ISSUE THREAD

**Issue by einorler** [ongr-io/ElasticsearchDSL#138]
Currently aggregations have to be added to the `ReverseNestedAggregation`, otherwise an exception will be thrown:
https://github.com/ongr-io/ElasticsearchDSL/blob/d218a69eb3230042f442d6f4dc88e1bd04c1338b/src/Aggregation/ReverseNestedAggregation.php#L75
Here is a use case: I want to aggregate on nested objects, but return the `doc_count` of the top level documents (because several nested objects can match). This can be achieved by:
```json
"aggs": {
    "color_nested": {
      "nested": {
        "path": "variants"
      },
      "aggs": {
        "color": {
          "terms": {
            "field": "variants.color"
          },
          "aggs": {
            "color_reverse": {
              "reverse_nested": {}
            }
          }
        }
      }
    }
  }
```
As illustrated by this query, in this case scenario there is no point in having additional aggregations and it is supported by Elasticsearch. I think we should remove the exception here, what do others think?

**Comment by ansata2001** [comment]
Yes, this exception would make sense on the NestedAggregation, not on the ReverseNested

**Comment by saimaz** [comment]
agree
