### ISSUE TITLE
Unnecessary processing of parameters in aggregations

### ISSUE THREAD

**Issue by einorler** [ongr-io/ElasticsearchDSL#147]
There are two aggregations that have `processArray()` in their `getArray()` methods. These calls should be removed:
https://github.com/ongr-io/ElasticsearchDSL/blob/1dc07a536cc831191d9eebb21deb462b7a4bcddb/src/Aggregation/DateHistogramAggregation.php#L85
https://github.com/ongr-io/ElasticsearchDSL/blob/1dc07a536cc831191d9eebb21deb462b7a4bcddb/src/Aggregation/TopHitsAggregation.php#L139

**Comment by saimaz** [comment]
Indeed. Let's fix this.
