### ISSUE TITLE
Consider to add elasticsearch-php to the composer.

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ElasticsearchDSL#151]
Maybe we should add elasticsearch-php client dependency in requirements.?

**Comment by bcremer** [comment]
Definitely in favor to add it.

Right know it's not clear which versions of `elasticsearch-php` are supported at all. The recently released version v5.0.0 of `elasticsearch-php` contains a alot of breaking changes.

It might be worth to also provide a compatibility matrix of `ongr-io/ElasticsearchDSL` , `elasticsearch-php` and `elasticsearch-bin`.

**Comment by saimaz** [comment]
As of 5.0 was released we will provide compatibility matrix if necessary. 

Currently, I'm testing ElasticsearchDSL in the ElasticsearchBundle and the latest stable version is fully compatible with both 2.4 and 5.0 versions.

**Comment by saimaz** [comment]
I investigated a bit more the relation between `elasticsearch-php` and `ElasticsearchDSL`. In a nutshell, I don't think so we there is a need to include `elasticsearch-php` in composer require. `ElasticsearchDSL` provides a DSL wich represents one to one elasticsearch query in the array manner. There is nothing related to elasticsearch client here, and it's up to the user what query he builds for 5.x or 2.x, at the end library doesn't care and allows to do it for every version.

If at any point I'm wrong please correct me and reopen the issue.
