### ISSUE TITLE
BoolQuery::getQueries with ie. BoolQuery::MUST triggers 'Undefined index: must'

### ISSUE THREAD

**Issue by niels-nijens** [ongr-io/ElasticsearchDSL#158]
For my particular use case I'm re-using the query (instances) in aggregations. When using the `BoolQuery::getQueries` method with a `$boolType` argument. It will trigger a notice that an array index is not defined when no query instances have been added to the boolType. 

From the docblock you'd assume that it would always return an (empty) array. Also because there's currently no other way to read the added query instances from the `BoolQuery` instance **with** the specified boolType.

I can provide a PR for this if you'd like.

**Comment by saimaz** [comment]
Thanks for the issue report! If you could provide a PR would be awesome ;)
