### ISSUE TITLE
MatchAllQuery() not working with Elasticsearch version 5 if no parameters are provided

### ISSUE THREAD

**Issue by nairolf** [ongr-io/ElasticsearchDSL#163]
If i instantiate an new MatchAllQuery Object with for example a boost of 1 `MatchAllQuery(['boost' => 1]) ` everything works as intended:
`"match_all":{"boost":1}`

However if i provide no parameters to `MatchAllQuery()`, the `getParameters()` returns an empty array which remains an array when encoded to JSON: 
`"match_all":[]`
That raises an exception inside Elasticsearch:

> [match_all] query malformed, no start_object after query name

Elasticsearch expects an object even if it is empty.

Expected JSON:
`"match_all":{}`

**Comment by saimaz** [comment]
Thanks for the report @nairolf. I will check.
