### ISSUE TITLE
Cannot set "size" parameter for TermsAggregation

### ISSUE THREAD

**Issue by runemoennike** [ongr-io/ElasticsearchDSL#171]
According to the ES documentation, when performing a "terms" aggregation, ElasticSearch will by default return the top 10 terms. If you want more, you have to pass an additional "size" parameter. 

However, there is no way to set that parameter on ONGR\ElasticsearchDSL\Aggregation\Bucketing\TermsAggregation .

It seems to me that this class (and perhaps other aggregation classes?) should either:

1. Have a getter/setter for the "size" parameter, or
2. Support an optional "parameters" array in the constructor allowing the passing of any additional parameters. This matches the classes in ONGR\ElasticsearchDSL\Query.

Of course option 2 is more flexible, but perhaps too much so?

I'd be happy to implement either one and make a PR, but I'd like to know that a solution is not already in the pipeline, and also get your input on which of the two options you'd prefer.

**Comment by runemoennike** [comment]
Sorry, my bad, after looking more at the source, I found that all aggregation classes already use the ParametersTrait which lets me use addParameter on the instance.

**Comment by saimaz** [comment]
It has to be more clear in the docs. I created the issue for docs update. Thanks @runemoennike. 

#172

**Comment by cpats007** [comment]
Hi. Sorry to report on a closed issue, but does this actually work? I'm currently trying to perform a TermsAggregation, and the data being returned is still the default top 10 results, despite setting the size to 500. I know there are something in the region of 20 different buckets coming back, but I'm only getting the top 10.

Code I'm using to set the aggregation:

```php
$thisAggregation = new TermsAggregation($fieldName);
$thisAggregation->setField($fieldName);
$thisAggregation->addParameter('size', $size);
```

Seeing this in the object:

![image](https://cloud.githubusercontent.com/assets/5278964/25002500/a92488fe-2042-11e7-8d5e-4e6b3509cae4.png)

and then this in the results:

![image](https://cloud.githubusercontent.com/assets/5278964/25002515/c0e50338-2042-11e7-97f9-3c235c295859.png)


As you can see it's not returning more than the top 10. Am I doing something wrong or is something not working properly? using `"ongr/elasticsearch-dsl": "~5.0"` in my composer file, so not sure if there is a more updated version?

Many thanks for the help.

**Comment by saimaz** [comment]
Reopening the issue to double-check if this is a bug or not. Thanks for the report with a good description what is wrong.

**Comment by cpats007** [comment]
No problem, thanks for the ultra quick response! :)

**Comment by cpats007** [comment]
Yep, pretty sure it's not working, as if you `json_encode()' the `->toArray()` function you get the following:

```json
{"terms":{"field":"advert_type"}}
```

no `size` included.

**Comment by cpats007** [comment]
Okay, so my apologies - it does work as intended, it was an issue with me setting the values in the wrong place - I'm sorry, but thanks once again for the excellent support. This can now be closed (again) 😄

**Comment by saimaz** [comment]
Good to know that everything is ok.
