### ISSUE TITLE
script_score query does not support [params] in ElasticSearch 5.0

### ISSUE THREAD

**Issue by KnysakPatryk** [ongr-io/ElasticsearchDSL#175]
https://www.elastic.co/guide/en/elasticsearch/guide/master/script-score.html

**Comment by saimaz** [comment]
Function score now has a different structure and don't use `script_score` if I don't miss anything. 

https://www.elastic.co/guide/en/elasticsearch/reference/5.1/query-dsl-function-score-query.html#function-script-score

Removing `params` might not solve the issue.

**Comment by saimaz** [comment]
My bad, actually `params` seems are still there in `5.x`: https://www.elastic.co/guide/en/elasticsearch/reference/5.1/query-dsl-function-score-query.html#function-script-score

**Comment by KnysakPatryk** [comment]
For now it's just throwing exception and kills the script (even if you don't use this feature). With this fix it's not throwing exception. But I know, for fixing this issue entirely, it's required to make futher changes.

**Comment by saimaz** [comment]
Let's take a look if there is possible to make some adjustments by keeping BC for 2.x Elasticsearch. If the `params` causes exception maybe it can be filtered out if this is an empty array?

**Comment by KnysakPatryk** [comment]
In my opinion we should BC. Even `elasticsearch/elasticsearch` recommends using v5 library with v5 ES. To be honest, this library is not working good with complicated queries accross different ES versions. If you don't believe me, just check it out by yourself.

**Comment by saimaz** [comment]
`elasticsearch/elasticsearch` v5 dropped 2.x support for a number of other reasons. Since this library just builds a query, it was ok.

This is the first example it causes search body differences. And if there is no solution, for sure I will release a new major version by dropping 2.x support as well.

**Comment by saimaz** [comment]
Related to #177

**Comment by saimaz** [comment]
Fixed in #186

**Comment by saimaz** [comment]
There is also a test PR (#189) which will check if function score is working correctly on 2.x and 5.x elasticsearch.
