### ISSUE TITLE
parsing_exception: no [query] registered for [missing] in ElasticSearch 5.0

### ISSUE THREAD

**Issue by KnysakPatryk** [ongr-io/ElasticsearchDSL#176]
Deprecated in 2.2.0.
Use exists query inside a must_not clause instead.

**Comment by saimaz** [comment]
Related to #177

**Comment by KnysakPatryk** [comment]
Missing Query is removed in ES 5.0.

**Comment by llwire** [comment]
Reference to `must_not` clause here, just in case someone is wondering: 

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-exists-query.html#_literal_missing_literal_query
