### ISSUE TITLE
Review differences in search body between Elasticsearch 2.x and 5.

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ElasticsearchDSL#177]
There were some issues where 's hard to keep BC across 2.x and 5.x. Most likely there is a need for the new major version by dropping support for Elasticsearch 2.x.

**Comment by KnysakPatryk** [comment]
@saimaz Hello! You tagged this issue as planned. Can you tell me when exactly do you want to work out this problem? This knowledge is really crucial for me, because I have planned migrating to ES 5.0, and this issue is blocking me. If you make the decission, I can help you with coding.

**Comment by saimaz** [comment]
Hi @KnysakPatryk, I'm working on this. The plan is to release at least RC or even stable until 1st of January.

**Comment by KnysakPatryk** [comment]
@saimaz I'm looking forward for this :)

**Comment by KnysakPatryk** [comment]
@saimaz Hello in 2017! How it's going with the library?

**Comment by saimaz** [comment]
Hi @KnysakPatryk, Happy new 2017 year. I split elasticsearch version support to 2.x and 5.x. There is updated matrix table in the readme. First of all the focus is on 5.0 support since 2.x I assume is working well. Any help, by testing/contribution is very welcome ;)

**Comment by KnysakPatryk** [comment]
Here is complete list of changes.
