### ISSUE TITLE
 Undefined index: namespace

### ISSUE THREAD

**Issue by Chitzi** [ongr-io/ElasticsearchDSL#187]
We are expecting an issue after a query.

After a query propelly executed when I'll try to use the data with a foreach appear this hateful error.
(I've tried with a enormous var_dump in the $results var, and all correct data are contain in it)

Bad Request. Error: "Notice: Undefined index: namespace"

Any idea?

**Comment by saimaz** [comment]
To help you I need to know how to reproduce the issue. Now `Bad Request. Error: "Notice: Undefined index: namespace"` Doesn't say anything.

Please provide:
- Elasticsearch version
- ElasticsearchDSL version
- PHP version
- Query you want to build
- The PHP code you are trying to execute

**Comment by Chitzi** [comment]
I know.

Elasticsearch version: 5.0.1
ElasticsearchDSL version: 2.2.0
PHP version 7.0.8
Query:
Get all air flights for a destination base on IATA code.

`$search_request_db = $this->em->getRepository('CoreBundle:Solutions')->createSearch();
$search_request_db->addQuery(new TermQuery('departure.airportCode', $departure->getAirportCode()));

$results = $this->em->getRepository('CoreBundle:Search')->execute($search_request_db);
`

This is just an example. Same error will be given also with a new MatchAll() or with even other fields.
In this case it gives me:

`echo count($results); // 8

foreach ($results as $document) {
	echo $document->date;exit; // Notice: Undefined index: namespace"
}
`

**Comment by saimaz** [comment]
Your query looks ok. There is nothing that might break something here.

What kind of exception there is? Is there related to PHP? Maybe there is some mistake in `Documents` some syntax error? 

Do you use elasticsearch type columns automatically generated or you defined your own? Like:

```php
    /**
     * @ES\Property(type="string", name="custom_title")
     */
    private $title;
```

**Comment by Chitzi** [comment]
It was a my error on document. 

```
     /**
     * @var LocationMetaObject
     *
     * @ES\Embedded(class="CoreBundle:Location")
     */
     private $destination;
```

Error was this:

```
     /**
     * @var string
     *
     * @ES\Embedded(class="CoreBundle:Location")
     */
     private $destination;
```
