### ISSUE TITLE
The docs should mention the namespaces that need to be used

### ISSUE THREAD

**Issue by SeinopSys** [ongr-io/ElasticsearchDSL#199]
In the latest update (5.0.0) some things were moved under a new namespace, such as `ONGR\ElasticsearchDSL\Query\BoolQuery` to `ONGR\ElasticsearchDSL\Query\Compound\BoolQuery` and `ONGR\ElasticsearchDSL\Query\TermQuery` to `ONGR\ElasticsearchDSL\Query\TermLevel\TermQuery`.

This change was seemingly done silently (without notice in the readme, for example), and I had to look through the source folders to find where all of the classes went, because my IDE was giving me errors. There is the message

>We won't include namespaces in any examples *[...]* all class's names are unique *[...]* any IDE editor should autocomplete and include it for you

but there are some statements here which are incorrect.

Not everyone uses an IDE, and those who code in Notepad++ (or similar) will have a hard time finding the (now even more well-hidden) classes. I personally **do** use one but in my honest opinion the docs should provide the information necessary to use the package and not an IDE's autocomplete feature, which, by the way, might also be turned off for some people.

You also can't know how others' code is structured, maybe they have classes with the same name somewhere. The class names might be unique inside your own module but not in the codebase it's being used in.

I originally thought autocomplete didn't work for ElasticsearchDSL at all because it wouldn't work for `MissingQuery` (mentioned [here](https://github.com/ongr-io/ElasticsearchDSL/blob/8d36311399563d74db2d0fe24ee237dc3000eba3/docs/HowTo/HowToSearch.md)) but by the looks of it that class has been removed from the codebase.

**Comment by saimaz** [comment]
Thank you for the feedback @SeinopSys. Sorry to hear you got a problem.

It's not a silent change.  In v2.2.2 this query grouping was introduced and marked with deprecations what will deprecate. Also in v5.0.0 release notes there is a [message](https://github.com/ongr-io/ElasticsearchDSL/releases/tag/5.0.0) about this 

I'm working on the docs, and the full upgrade guide will be pushed as well very soon to the repo. It was released quicker to not stop the ElasticsearchBundle development to support 5.x Elasticsearch.

This is the major version wich most likely will stick a while. So I took a chance to group the queries like aggregations to keep the same order in the library. Grouping queries makes much much easier for me to maintain them. And ElasticsearchBundle might get some benefits of that.

**Comment by SeinopSys** [comment]
Fair enough. From now on I will always check the releases whenever I see a new version come out, I admit not checking that before. I somehow skipped v2.2.2 and was updated to 5.0.0 straight away just now, so it seemed confusing. I'm glad to hear the docs are being worked on, and thank you for making and maintaining this useful library.
