### ISSUE TITLE
Add support for multisearch queries

### ISSUE THREAD

**Issue by Dariusp** [ongr-io/ElasticsearchDSL#204]
Add support to build set of queries for multi search API.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html

**Comment by saimaz** [comment]
After a long long time of thinking :) I think this is not should be handled in this library. This library purpose it to generate a query, not many queries, so it has to be implemented in e.g. ElasticsearchBundle instead.
