### ISSUE TITLE
Unable to generate "_source" in query.

### ISSUE THREAD

**Issue by murnieza** [ongr-io/ElasticsearchDSL#230]
There is not way to add "_source" to query JSON body as described in https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html

**Comment by toooni** [comment]
It seems to work with `$search->addUriParam('_source_exclude', ["variations.*"]);`. I found it because of the `in_array` check in `Search::addUriParam`.
The best solution IMO should be to change the setSource option to accept an array.

**Comment by murnieza** [comment]
@toooni you don't have to add an array to URI. It can be coma separated list of fields: `$search->addUriParam('_source_exclude', 'variations.*,slug,some_field')`.

Also adding `_source` as JSON query body and adding `_source` as an URI parameter is not always the same. 
It will produce the same affect for `hits`, but will not be applied on `inner_hits` you must put it into the JSON.

**Comment by toooni** [comment]
@murnieza thank you for clarification.

**Comment by saimaz** [comment]
I assume this issue is closed now.
