### ISSUE TITLE
Support for TermLevel Missing queries

### ISSUE THREAD

**Issue by andrewmclagan** [ongr-io/ElasticsearchDSL#232]
see https://www.elastic.co/guide/en/elasticsearch/guide/current/_dealing_with_null_values.html#_missing_query

Let me know if there is an alternate approach to this otherwise I could do a PR

**Comment by sirago** [comment]
Also interested in this

**Comment by romainjanvier** [comment]
You can perform this with a "should not exists" query.

See https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-exists-query.html#_literal_missing_literal_query

ie 
`
$search->addQuery(new ExistsQuery('myField'), BoolQuery::MUST_NOT);
`

**Comment by saimaz** [comment]
Thank you @romainjanvier for the suggestion. It's a perfect solution for this problem.

`missing` and filters were removed from the elastic search and now are gone in this DSL library as well.
