### ISSUE TITLE
[QUESTION] How to enable "track_scores" in version 2.x

### ISSUE THREAD

**Issue by trandangtri** [ongr-io/ElasticsearchDSL#234]
Dear guys,

We are using Elasticsearch 2.x and ElasticsearchDSL version 2.x too. Based on our needs, we need to enable `track_scores` in Search request. So I just want to know are there any way to enable this config in version 2.x? Seems it's supported in ElasticsearchDSL version 5.x afak.

Thanks so much

**Comment by saimaz** [comment]
Hi @trandangtri, in 2.x it is not supported. The only way to get it work is to add a support. What has to be done here is to add in `getQueryParams` the required key and the variable to hold it.

btw 2.x is getting old, is there any reason why you don't upgrade to 5.x of the elasticsearch?

**Comment by trandangtri** [comment]
Thanks @saimaz for your quick response. 
As an ad-hoc solution, I override `ONGR\ElasticsearchDSL\Search` as below, and it works as my expectation

```php
namespace AcmeBundle\Service\ONGR\ElasticsearchDSL;

use ONGR\ElasticsearchDSL\Search as OngrSearch;

/**
 * Class Search
 * @package AcmeBundle\Service\ONGR\ElasticsearchDSL
 */
class Search extends OngrSearch
{
    /**
     * @var bool
     */
    private $trackScores;

    /**
     * @param bool $trackScores
     *
     * @return Search
     */
    public function setTrackScores(bool $trackScores): Search
    {
        $this->trackScores = $trackScores;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function toArray()
    {
        $output = parent::toArray();
        if ($this->trackScores) {
                $output['track_scores'] = $this->trackScores;
        }

        return $output;
    }
}
```

And FYI, the existing system of our client is still using ES 2.4 and they don't have any plan to upgrade to the new one yet.
