### ISSUE TITLE
Where is Sorts() ?

### ISSUE THREAD

**Issue by milesich** [ongr-io/ElasticsearchDSL#242]
In the example at http://docs.ongr.io/ElasticsearchDSL/Aggregation/TopHits you are using `Sorts()` object but I cannot find in. 

It was deleted in this commit https://github.com/ongr-io/ElasticsearchDSL/commit/8e6b7f673b3d4ae486fee18ce5083466ec1b6a0f 

How can I use it today?

**Comment by Kuri-su** [comment]
I also encountered the same question

**Comment by saimaz** [comment]
That is kind'a deprecated place. Will update it. Thank for the notice.

**Comment by saimaz** [comment]
@milesich you can use sorts by using `FieldSort` class and adding it even multiple times as much as by much fields you wanna sort. Will add it to the docs as well.
