### ISSUE TITLE
How to build a complicated query with nested logic?

### ISSUE THREAD

**Issue by EdenChan** [ongr-io/ElasticsearchDSL#244]
I find this package is quite helpful but I am still confused about how to form a more complicated query.

for example:
 **select * from goods where ((color='black' and price < 100) or (color='yellow' and price between 50 and 150));**

**Comment by EdenChan** [comment]
modify

**Comment by saimaz** [comment]
This is sql query :). You know that this library is for elasticsearch, right?

**Comment by EdenChan** [comment]
yes, i want to know how to transform such sql with a bit complicated logic into es dsl using this package, since it could transform most sql into dsl conveniently.
