### ISSUE TITLE
Any chance for elasticsearch 6 support ?

### ISSUE THREAD

**Issue by macnibblet** [ongr-io/ElasticsearchDSL#245]

**Comment by keithburgoyne** [comment]
I second this question.

**Comment by saimaz** [comment]
Yes! There is a huge chance. I'm investigating the required changes for the ES 6 support. The thing is that I want to make sure that the whole ONGR ecosystem could support the new version. If for some reason won't be possible I will release only the DSL library update.

**Comment by macnibblet** [comment]
Cool !

**Comment by saimaz** [comment]
[6 beta](https://github.com/ongr-io/ElasticsearchDSL/releases/tag/v6.0.0-beta) released.

**Comment by macnibblet** [comment]
Lovely!
