### ISSUE TITLE
Support for symfony/serializer 4.0

### ISSUE THREAD

**Issue by reyostallenberg** [ongr-io/ElasticsearchDSL#248]
Are there any plans to support symfony/serializer 4.0 ?
Is there a way to help with this for me?

As I take a look at https://github.com/symfony/serializer/blob/master/CHANGELOG.md there are only 2 removals in 4.0.* and they aren't used in ElasticsearchDSL.

But I haven't checked the requirements of symfony/serializer itself .

**Comment by reyostallenberg** [comment]
Sorry, duplicate of #243 so can be closed

**Comment by saimaz** [comment]
Added in 6 beta version

**Comment by saimaz** [comment]
I would appreciate any feedback on this new version if you can test with your project.

**Comment by saimaz** [comment]
btw I will add Symfony 4.0 support to the 5.x versions as well ;)
