### ISSUE TITLE
FunctionScoreQuery->addDecayFunction missing weight

### ISSUE THREAD

**Issue by martiis** [ongr-io/ElasticsearchDSL#261]
Add `weight` to `FunctionScoreQuery->addDecayFunction`. Now only possible way to add weight to decay functions are by using `FunctionScoreQuery->addSimpleFunction`.

**Comment by martiis** [comment]
it does this

```
{
    "gauss": {
        "<field>": {...}
        "weight": 5
    },
}
```
while it should be here
```
{
    "gauss": {...},
    "weight": 5
}
```

at least in `elasticsearch 6.2.3`

**Comment by saimaz** [comment]
ok that's make sense

**Comment by saimaz** [comment]
Added in `v5.0.3` and `v6.0.1`

**Comment by martiis** [comment]
👍
