### ISSUE TITLE
ParametersTrait::addParameter() to return self 

### ISSUE THREAD

**Issue by mab-on** [ongr-io/ElasticsearchDSL#303]
It would be nice if ONGR \ ElasticsearchDSL \ ParametersTrait :: addParameter would return self  (same way it is implemented in ParametersTrait :: setParameters () already).

**Comment by saimaz** [comment]
I will add this, thanks for the hint @mab-on

**Comment by ilvalerione** [comment]
There's a pending pull request to integrate this behaviour. @saimaz if you need something different than I coded, comment my pull request, I'll apply the changes.

**Comment by saimaz** [comment]
It's already merged. Will be released soon ;)
