### ISSUE TITLE
Incompatible change in latest releases

### ISSUE THREAD

**Issue by lionslair** [ongr-io/ElasticsearchDSL#309]
I have tried both the new 6.1.1 and 7.1.1 release and both have this issue. you have type cast the format as a string here 
https://github.com/ongr-io/ElasticsearchDSL/compare/v6.1.0...v6.1.1#diff-cb1a75a63f82e327dba8abc2429a07efR25

That is incompatible with the interface
`    /**
     * {@inheritdoc}
     */
    public function normalize($data, $format = null, array $context = [])
`

Error being produced is 
PHP Fatal error:  Declaration of ONGR\ElasticsearchDSL\Serializer\OrderedSerializer::normalize($data, ?string $format = NULL, array $context = Array) must be compatible with Symfony\Component\Serializer\Serializer::normalize($data, $format = NULL, array $context = Array) in /vendor/ongr/elasticsearch-dsl/src/Serializer/OrderedSerializer.php on line 88

**Comment by lionslair** [comment]
This might be related to the fact laravel is locked to 4.x for symfony components
https://github.com/laravel/framework/blob/6.x/composer.json#L34

but version 7 will be using 5.x
https://github.com/laravel/framework/blob/7.x/composer.json#L34

**Comment by breta-ionut** [comment]
+1 to this. 6.1.1 and 7.1.1 will work with Symfony Serializer 5.* but won't work with 3.* and 4.*.

**Comment by saimaz** [comment]
Fixed in latest v6.2 and v7.2

**Comment by saimaz** [comment]
6.1.2 and 7.1.2 will support serializer 3.* and 4.* while the new 6.2.0 and 7.2.0 will support only serializer 5.0

I didn't find a decent way to support all 3 versions in the same source. Anyway, eventually there should be an upgrade to symfony 5 components so I don't take as a drawback.
