### ISSUE TITLE
Normalizer must be compatible with Symfony Normalizer

### ISSUE THREAD

**Issue by safwanghamrawi** [ongr-io/ElasticsearchDSL#315]
Hello,
by updating symfony from **4.3** to **4.4**, I have this issue (and other of the same type)
I have **"ongr/elasticsearch-dsl": "^7.0"** in composer which install the version **7.1.1**
Compile Error: Declaration of ONGR\ElasticsearchDSL\Serializer\Normalizer\CustomReferencedNormalizer::supportsNormalization($data, ?string $format = NULL) must be compatible with Symfony\Component\Serializer\Normalizer\NormalizerInterface::supportsNormalization($data, $format = NULL)

Thanks

**Comment by alejobit** [comment]
You must update to version v7.1.2
