### ISSUE TITLE
CustomReferencedNormalizer (v7.1.1) must be compatible with CustomNormalizer (v.3.4.37)

### ISSUE THREAD

**Issue by esynaps** [ongr-io/ElasticsearchDSL#317]
https://github.com/ongr-io/ElasticsearchDSL/blob/b7653ed32d6d5b65aeef3b7ef4f46e7ac069c393/src/Serializer/Normalizer/CustomReferencedNormalizer.php#L29

does not comply with

https://github.com/symfony/serializer/blob/f8b99832d016e2d2c77c797c3df561adecd33dd3/Normalizer/CustomNormalizer.php#L30

These constraints are not correct

` "symfony/serializer": "^3.0|^4.0|^5.0"`

**Comment by malvindake** [comment]
Solved by downgrading to 5.x
composer require ongr/elasticsearch-dsl:5.x

**Comment by einorler** [comment]
This is solved in `v7.1.2` which is using sf 4 normalizer, sf 5 normalizer is now used in `v7.2`
