### ISSUE TITLE
include ES 2.0 in travis testing env

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ElasticsearchDSL#33]
Right now we are using only simpel elasticsearch service provided from travis. Lets include custom ES versions the latest 1.* and 2.*

Same as here: https://github.com/ongr-io/ElasticsearchBundle/issues/453

**Comment by kazgurs** [comment]
ongr-io/ElasticsearchDSL#47

**Comment by saimaz** [comment]
@kazgurs next time add in PR description that you closing some issue with this PR. I corrected your PR description.
