### ISSUE TITLE
Support Symfony 4.4

### ISSUE THREAD

**Issue by shyim** [ongr-io/ElasticsearchDSL#335]
The 7.2 version is unusable for Projects depending on Symfony LTS (4.4).

Can you maybe consider supporting Symfony 4.4 and 5?

https://github.com/ongr-io/ElasticsearchDSL/blob/7.2/composer.json#L15

**Comment by Ocramius** [comment]
v5 is already supported in `7.2.2`: 

https://github.com/ongr-io/ElasticsearchDSL/blob/c0789c35e8738c2b1138c8d33ec9fbcd740c909d/composer.json#L15
