### ISSUE TITLE
DateHistogramAggregation does not support TimeZone

### ISSUE THREAD

**Issue by patrickkusebauch** [ongr-io/ElasticsearchDSL#343]
From ES official docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html#_time_zone_2

There is no equivalent in the code.

**Comment by patrickkusebauch** [comment]
Never mind, found out how to add custom params. Might be nice to have it via a custom method, though.

**Comment by rbertram90** [comment]
For others searching for this:
```
$agg = new DateHistogramAggregation($name, $field, $interval, $format);
$agg->addParameter('time_zone', date_default_timezone_get());
```
