### ISSUE TITLE
If FunctionScore does not have any functions breaks query

### ISSUE THREAD

**Issue by martiis** [ongr-io/ElasticsearchDSL#36]

**Comment by asev** [comment]
The same is with empty bool query, empty filtered query and other queries that behaviour is defined through setters (not constructor).
At this moment elasticsearch itself throws quite readable error in such cases (of course with all query dumped in the error).

It is open for discussion if ElasticsearchDSL should validate these queries.

**Comment by murnieza** [comment]
I think that it could be too much effort to maintain all possible cases when this could happen.

**Comment by murnieza** [comment]
@saimaz, @mvar what's your opinion?

**Comment by saimaz** [comment]
That would be a massive responsibility to validate whole queries. We cannot validate one scenario, so it's all or none. The exception in query if there is no function set coud be a solution for better error handling, but as I said previosly, query validation we should take very carefully.

**Comment by saimaz** [comment]
After long discussions and investigation. We believe that query structure validation is currently not a DSL responsibility. We simply providing a way to generate an array in objective perspective by asuming the user knows what he is writing. 

Query validation should be performed in the native client as lowest part in the chain.
