### ISSUE TITLE
Support other parameters in termsAggregation

### ISSUE THREAD

**Issue by nalscher** [ongr-io/ElasticsearchDSL#71]
Hello,

According to this documentation
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html

Terms Aggregation can support many parameters : 
size, min_doc_count, order,...

Can you add to this ?
Thanks

**Comment by saimaz** [comment]
You can add any parameter via `ParametersTrait`

here's an example:

```php
$termsAggregation = new TermsAggregation('genders', 'gender');
$termsAggregation->addParameter('size', 5);
$termsAggregation->addParameter('min_doc_count', 3);

$search = new Search();
$search->addAggregation($termsAggregation);

$queryArray = $search->toArray();
```

**Comment by nalscher** [comment]
Ok sorry... thanks for your help !!
