### ISSUE TITLE
Add "type" support to IdsQuery

### ISSUE THREAD

**Issue by tompoc** [ongr-io/ElasticsearchDSL#85]
Filters documents that only have the provided ids. Note, this query uses the [_uid](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-uid-field.html) field.
```json
{
    "ids" : {
        "type" : "my_type",
        "values" : ["1", "4", "100"]
    }
}
```

The type is optional and can be omitted, and can also accept an array of values. If no type is specified, all types defined in the index mapping are tried.

**Comment by einorler** [comment]
@saimaz do you really think we should introduce a separate attribute for type? The query already uses ParametersTrait, type can be passed as a parameter

**Comment by saimaz** [comment]
You are right @einorler. The library does not support any custom fields for any query. You can add whatever you want as a parameter.
