### ISSUE TITLE
FiltersAggregation generates invalid array

### ISSUE THREAD

**Issue by niels-nijens** [ongr-io/ElasticsearchDSL#91]
The [FiltersAggregation](https://github.com/ongr-io/ElasticsearchDSL/blob/6ba9a7810e6aa5653de79dd2615016135ead408e/src/Aggregation/FiltersAggregation.php#L80-L82) adds filters inside an array with the type as key. Though, this generates the following array for a `TermQuery` with the 'term'-key twice in the stack:

``` php
array(
    'filtername' => array(
        'term' => array(
            'term' => array(
                'fieldname' => 'fieldvalue'
            )
        )
    )
)
```

This filter will throw an exception when sending it with a query to an Elasticsearch server.

I can supply a PR to fix this issue if you want.

**Comment by saimaz** [comment]
Sure, you are welcome to open a PR.
