### ISSUE TITLE
Check if there are any new queries or aggs that we still do not support.

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ElasticsearchDSL#97]

**Comment by RonRademaker** [comment]
Looks like https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#query-dsl-match-query-phrase and https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#query-dsl-match-query-phrase-prefix are missing, or am I missing something?

I'm planning on creating one for the latter and can put it in a PR if you like.

**Comment by saimaz** [comment]
Hey @RonRademaker! If you could make a PR with those missing queries we would appreciate a lot ;).

**Comment by saimaz** [comment]
Great work @einorler, but you are missing the docs page for every query.
